### ISSUE TITLE
Crash when using ACES OCIOv2 config

### ISSUE THREAD

**Issue by MrLixm** [mteillet/PyVexr#2]
Hey there again.

# Context

- version 0.0.3
- Windows 10

# Issue

The application crash after a restart when the OCIO config was set to use the [official ACES CG config ](https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES/releases/tag/v1.0.0).

```
F:\softwares\apps\pyvexr\0.0.3\dist>pyVexr_gui.exe
Loaded ocio config and preferences
qt.qpa.fonts: Unable to enumerate family ' "Segoe UI Variable Static Display" '
qt.qpa.fonts: Unable to enumerate family ' "Segoe UI Variable Static Display" '
Traceback (most recent call last):
  File "pyVexr_gui.py", line 1556, in run
  File "pyVexr_main.py", line 31, in bufferBackEnd
  File "pyVexr_main.py", line 445, in convertExr
  File "pyVexr_main.py", line 512, in ocioTransform2
PyOpenColorIO.Exception: LegacyViewingPipeline is not valid: DisplayViewTransform: empty source color space name. 
```

Content of the `config.json`

```json
{"ocioVar": "F:\\softwares\\apps\\ocio\\configs\\aces-official\\cg-2.0.0\\1.0.0\\cg-config-v1.0.0_aces-v1.3_ocio-v2.0.ocio", "ocioIn": "", "ocioOut": "ACES 1.0 - SDR Video", "ocioDisplay": "", "ocioLook": "None"}
```

# Steps to reproduce

- Open the application
- Go into the OCIO menu to change the configuration
- Set the path to the one of the mentioned ACES config
- The interface update but the `Input interpreation` is empty.
- Click "Save OCIO settings"
- Click Ok on the dialog
- Application seems to crash
- Restart the application
- Application crash again and won't open anymore. (because of the fault save config.json)

# Expected behavior

I can use the official ACES CG config as the application mention it supports OCIOv2 config.

---
Cheers !

**Comment by MrLixm** [comment]
Same issue with a custom OCIO v1 config : https://github.com/MrLixm/AgXc/blob/main/ocio/config.ocio

**Comment by mteillet** [comment]
Hello :)

Just tested both configs, and made the changes to avoid crashes when the display names did not match the ocio I previously defaulted the PyVexr to. It should work now, was tested with both the ACES CG V1 and ACES CG V2 configs and will be available in the next windows/linux releases.

![image](https://user-images.githubusercontent.com/54497763/209082311-863ce974-2ae6-464e-8c90-ae72f1a4ce13.png)

Fixed on this commit (and the following one)
[https://github.com/mteillet/PyVexr/commit/f483a36973ed425d696211c87d84a2a9c71f1c5c](url)

Thanks again for your feedback, cheers !

Martin
